// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdd91giv3vrrDy6bvu2pi2agPwlv8cKnU',
    appId: '1:757104425829:web:39846aebaab8ceb011ff8c',
    messagingSenderId: '757104425829',
    projectId: 'myukapp-3c3b8',
    authDomain: 'myukapp-3c3b8.firebaseapp.com',
    databaseURL: 'https://myukapp-3c3b8-default-rtdb.firebaseio.com',
    storageBucket: 'myukapp-3c3b8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8AEnzssn7ce6gXghmn--M0mi0hlvoy50',
    appId: '1:757104425829:android:584e408292dd08b411ff8c',
    messagingSenderId: '757104425829',
    projectId: 'myukapp-3c3b8',
    databaseURL: 'https://myukapp-3c3b8-default-rtdb.firebaseio.com',
    storageBucket: 'myukapp-3c3b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsYGjIB1vGk6vlstud4ZICqWfY_nOAShA',
    appId: '1:757104425829:ios:f0fd5aacdd64e5f111ff8c',
    messagingSenderId: '757104425829',
    projectId: 'myukapp-3c3b8',
    databaseURL: 'https://myukapp-3c3b8-default-rtdb.firebaseio.com',
    storageBucket: 'myukapp-3c3b8.appspot.com',
    iosClientId: '757104425829-posm706dlmioc0ofqak8uiufdke4rs1k.apps.googleusercontent.com',
    iosBundleId: 'com.singhthatcodes.myukapp',
  );
}
